-- phpMyAdmin SQL Dump
-- version 3.5.2.2
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Jun 01, 2014 at 04:43 PM
-- Server version: 5.5.27
-- PHP Version: 5.4.7

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `9bookstore`
--

-- --------------------------------------------------------

--
-- Table structure for table `books`
--

CREATE TABLE IF NOT EXISTS `books` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `isbn` varchar(255) NOT NULL,
  `isbn10` varchar(255) NOT NULL,
  `audience` varchar(255) NOT NULL,
  `format` varchar(255) NOT NULL,
  `language` varchar(255) NOT NULL,
  `pages` int(3) NOT NULL,
  `published` date NOT NULL,
  `dimensions` varchar(255) NOT NULL,
  `weight` int(4) NOT NULL,
  `genre` varchar(255) NOT NULL,
  `description` longtext NOT NULL,
  `price` int(7) NOT NULL,
  `image` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=32 ;

--
-- Dumping data for table `books`
--

INSERT INTO `books` (`id`, `name`, `isbn`, `isbn10`, `audience`, `format`, `language`, `pages`, `published`, `dimensions`, `weight`, `genre`, `description`, `price`, `image`) VALUES
(1, 'Inferno', '9780714838151', '0714838152', 'General ', 'Hardcover ', 'English ', 480, '1999-01-01', '38.0 x 28.4  x 5.5', 390, 'Fiction', 'This is the only major monograph of humanitarian and photojournalist James Nachtwey, five-time winner of the Robert Capa Medal for Photography. \r\n\r\nFeaturing brutally compassionate photographs taken from 1990-99, inspired by an overwhelming belief in the human possibility of change, this volume is a definitive selection from Nachtwey''s astonishing portfolio. \r\n\r\nIt documents today''s conflicts and their victims, from Somalia''s famine to genocide in Rwanda, from Romania''s abandoned orphans and ''irrecoverables'' to the lives of India''s ''untouchables'', from war in Bosnia to conflict in Chechnya. Inferno is an evocative visual insight into modern history, bringing it disturbingly close to our consciousness.   \r\n', 170000, 'inferno.jpg'),
(2, 'Possesion', '9780451465221', '0451465229', 'General', 'Paperback', 'English', 564, '2014-05-06', '17.0 x 10.9  x 3.8', 270, 'Fantasy', 'Jim Heron, disgruntled fallen angel, thinks that he finally has a leg up against Devinia, a devil''s minion, in their fight over seven souls to end the war against good and evil. This is because Jim knows exactly which earthly soul he needs to save: a distant single father of a 13-year-old son. Luckily, Jim thinks that he can leverage the power of love, because this man is in love with a careful woman previously burnt by lust. So instead, Jim focuses his attentions on Sissy, the young soul he saved from Devinia''s clutches, who is now transitioning to her life as an angel. But things are more complicated than they seem, because someone else is in love with that careful woman--the twin of the man whose soul needs saving. And unfortunately, this twin is the better contender for romance--he''s a good-hearted sensitive musician. Torn between gentle support and steamy passion, will this woman make the choice that brings a brooding, broken soul to redemption? Or will that soul be doomed to endure the most hellish possession?', 376000, 'possession.jpg'),
(4, 'The Blue Mile', '9781742613918', '1742613918	', 'General', 'Paperback', 'English ', 464, '2014-05-01', '23.1 x 15.3  x 3.3 ', 560, 'Fiction', 'The week before Christmas, 1929, Eoghan O''Keenan loses his factory job, and has to flee the slums of Chippendale with his seven-year-old sister Agnes. \r\n\r\nOn the north side of Sydney at Lavender Bay, Olivia Greene is working on her latest millinery creations and dreaming of becoming the next Coco Chanel. \r\n\r\nA job on the Harbour Bridge for Eoghan, designing couture for the Governor''s wife for Olivia, and a chance meeting in the Botanic Gardens sees the beginning of an unconventional romance. From vastly different backgrounds, with absolutely nothing in common - from faith to wealth and class - it seems that the blue mile of harbour between Olivia and Eoghan will be the least of the obstacles ahead. \r\n\r\nBy mid-1932, as the construction of the Bridge is completed, the city is in chaos as the Great Depression begins to bite hard and the unemployed edge ever closer to a violent revolt. \r\n\r\nAnd then Eoghan disappears. \r\n\r\nSet against the spectacular backdrop of Sydney Harbour, The Blue Mile is a tale of the both wild and calculated risks a city took to build a wonder of the world, and of those taken by ordinary people to save a great love, against all of the odds. ', 125000, 'the-blue-mile.jpg'),
(5, 'Lick', '9781743517666', '1743517661', 'General ', 'Paperback ', 'English', 304, '2014-05-01', '23.1 x 15.4  x 2.2 ', 380, 'Fiction', 'Evelyn Thomas''s plans for celebrating her twenty-first birthday in Las Vegas were big. Huge. But she sure as hell never meant to wake up on the bathroom floor with a hangover to rival the black plague, a very attractive half-naked tattooed man, and a diamond on her finger large enough to scare King Kong. Now if she could just remember how it all happened. One thing is for certain, being married to rock and roll''s favourite son is sure to be a wild ride. ', 87000, 'lick.jpg'),
(6, 'Fool Me Twice', '9781476741352', '1476741352', 'General ', 'Paperback ', 'English', 400, '2014-05-01', '16.76 x 10.41  x 3.3 ', 180, 'Romance', 'Sensible and lonely, Olivia Mather survives by her wits—and her strict policy of avoiding trouble. But when she realizes that the Duke of Marwick might hold the secrets of her family''s past, she does the unthinkable, infiltrating his household as a maid. She''ll clean his study and rifle through his papers looking for information.\r\n\r\nAlastair de Grey has a single reason to live: vengeance. More beautiful than Lucifer, twice as feared, and thrice as cunning, he''ll use any weapon to punish those who fooled and betrayed him—even an impertinent maid who doesn''t know her place. But the more fascinated he becomes with the uppity redhead, the more dangerous his carefully designed plot becomes. For the one contingency he forgot to plan for was falling in love . . . and he cannot survive being fooled again.\r\n', 80000, 'fool-me-twice.jpg'),
(7, 'Giving In', '9780425272961', '0425272966', 'General ', 'Paperback', 'English', 291, '2014-05-06', '20.8 x 13.7  x 2.3 ', 270, 'Romance', 'In her sensational Breathless Trilogy, New York Times bestselling author Maya Banks tested the boundaries of desire. In her new trilogy, there’s only one thing left to do: cross them. Now, the story continues as one woman, haunted by the shadows of the past, explores the possibilities of a new beginning in ways she never could have imagined… \r\n\r\nKylie sees the way Jensen looks at her. The dark promise in his eyes. That rough edge of dominance she knows he possesses. But dominance is the one thing that frightens her above all else. She and her brother barely survived a childhood steeped in violence and abuse. She could never give up total control and submit to a man. Especially a man like Jensen. Could she? \r\n\r\nJensen sees the shadows in Kylie’s eyes. Knows he has to tread very carefully or risk losing any chance he has with her. All he wants is the opportunity to show her that dominance doesn’t equal pain, bondage or discipline. That emotional surrender is the most powerful of all, and that to submit fully to him will fulfill the aching void in her heart in a way nothing else ever will. \r\n ', 210000, 'giving-in.jpg'),
(8, 'Charlotte''s Creeks', '9781743319178', '1743319177', 'General ', 'Paperback ', 'English ', 446, '2014-05-01', '23.4 x 15.3  x 3.3', 580, 'Fiction', 'After a couple of years working in a privileged private school, Lucy Francis yearns for adventure. So when she hears about a job teaching four children on a massive cattle property in North Queensland, she decides to throw caution - and her teaching job - to the winds.\r\n\r\nWhen Lucy arrives at Charlotte''s Creek Station she finds a family in crisis. To make matters worse, the four children she''s been charged with educating are very spirited, not always cooperative, and dismally behind in their schooling.\r\n\r\nTo Lucy, the only person who seems to be keeping Charlotte''s Creek afloat is the family''s gruff stockman, Ted. With his support and encouragement Lucy throws herself into the day-to-day activities of the station and makes excellent progress with the children.\r\n\r\nThough Lucy and Ted''s feelings for each other grow, Ted can''t see any future for them because of his lack of prospects. As the family divisions at Charlotte''s Creek prove insurmountable and the property looks set to be put on the market, Lucy faces returning to the city and leaving Ted behind. . .\r\n\r\nBy the betselling author of Redstone Station, this is the story of a strong young woman stepping into the unknown, trying to make things work, and finding love.\r\n', 450000, 'charlotte-s-creek.jpg'),
(9, 'Saree', '9781922052933', '1922052930', 'General ', 'Paperback ', 'English ', 560, '2014-05-01', '38.0 x 28.4  x 5.5', 780, 'Fiction', 'Nila wasn''t born beautiful and is destined to go through life unnoticed... until she becomes a saree maker. As she works, Nila weaves into the silk a pattern of love, hope and devotion, which will prove to be invaluable to more lives than her own.\r\n\r\nFrom the lush beauty of Sri Lanka, ravaged by bloody civil war, to India and its eventual resting place in Australia, this is the story of a precious saree and the lives it changes forever. Nila must find peace, Mahinda yearns for his true calling, Pilar is haunted by a terrible choice, Sarojini doubts her ability to love, Madhav is a holy fraud and Marion''s understanding of the very meaning of love is challenged and transformed. Each teeters between joy and pain, and each is touched by the power and beauty of the saree.\r\n\r\nA breathtaking story of beauty, oppression and freedom... and of an enduring love that can never be broken.\r\n', 250000, 'saree.jpg'),
(10, 'Burning It Down', '9781623802301', '1623802300', 'General ', 'Paperback', 'English', 284, '2012-12-01', '22.9 x 15.2  x 1.5 ', 380, '', '"A CalPac Crew Novel " When newly promoted fire battalion chief Owen Douglas skips out on physical therapy after an on-the-job injury, his one-time hookup, Brad Sundstrom, bullies him into joining the adaptive rowing program at the Capital City Rowing Club. There, Owen meets Adam Lennox, a veterinarian and former rower who also works as a volunteer. Adam is new in town and eager to make friends, but the chemistry between him and Owen is blistering. Despite Owen''s commitment issues, he wants more this time. He makes a move, and the friendship he shares with Adam turns into more. But Adam hasn''t left his past as far behind as he thought. When his abusive ex-boyfriend, Jordan Sanders, returns, Adam and Owen find themselves in grave danger. Jordan won''t let anything stop him from getting Adam back-not even a court order. Soon Adam has to choose between breaking up with Owen to save him from Jordan''s fury or risking both their lives to stay by Owen''s side.', 455000, 'burning-it-down111.jpg'),
(11, 'Air Bound', '9780515154634', '0515154636', 'General', 'Paperback ', 'English', 400, '2014-05-27', '17.3 x 14.0  x 2.7 ', 200, 'Fantasy', 'The sisters of Sea Haven, bound by the heart and the magical power of the elements, return in this soul-stirring new novel from Christine Feehan, #1 New York Times bestselling author of Spirit Bound... \r\n\r\nFor as far back as she can remember, Airiana Ridell has always been aware of her extraordinary gift. She can intuit revealing and illuminating “patterns” in the air around her—whether in a spray of mist, in billowing clouds, or in the dense swirls of an impenetrable fog. Her abilities led to her placement in a secret government training facility when she was a child, but everything changed after her mother was murdered. \r\n\r\nAiriana fled the program, but she couldn’t outrun the desperate members of a shadowy cabal who want her, who need her, who will kill to get her. Kidnapped and held aboard a ship bound for dangerous seas, her only chance for rescue is Maxim Prakenskii. He has his reasons for helping her, but he isn’t about to reveal them to Airiana. Not yet. Not as the two are drawn together as moth to flame. Not when there are so many secrets yet untold that could shatter the quaint community of Sea Haven and all who reside there… \r\n', 234999, 'air-bound.jpg'),
(12, '8', '9781742831893', '1742831893	', 'Children ', 'Paperback', 'English', 192, '2014-05-01', '19.8 x 12.9', 200, 'Children''s', 'Sam''s nightmares become more unpredictable, and even more dangerous, as he seeks the next Dreamer. His search takes him to Cuba, where unknown pursuers, long-forgotten treasure and the perils of the ocean await. Meanwhile, Eva and Lora''s safety hangs in the balance, and Alex makes a terrifying discovery of his own...\r\n\r\nEnemies are closing in on all sides. Can Sam and his friends stay one step ahead and find the next Gear in time? Sam must find the last 13. They alone can save us. ', 20000, '8.jpg'),
(13, 'The Eye Of zoltar', '9781444707274', '1444707272', 'Teenager / Young Adult ', 'Hardcover ', 'English', 304, '2014-04-10', '20.3 x 13.2  x 3.6', 490, 'Children''s', 'The Mighty Shandar, the most powerful wizard the world has ever seen, returns to the Ununited Kingdoms. Clearly, he didn''t solve the Dragon Problem, and must hand back his fee: eighteen dray-weights of gold.But the Mighty Shandar doesn''t do refunds, and instead vows to eliminate the dragons once and for all - unless sixteen-year-old Jennifer Strange and her sidekicks from the Kazam house of enchantment can bring him the legendary jewel, The Eye of Zoltar.The only thing that stands in their way is a perilous journey with a 50% Fatality Index - through the Cambrian Empire to the Leviathan Graveyard, at the top of the deadly Cadir Idris mountain. It''s a quest like never before, and Jennifer soon finds herself fighting not just for her life, but for everything she knows and loves...\r\n', 245000, 'the-eye-of-zoltar.jpg'),
(14, 'Strawberry Thief', '9781742979960', '1742979963', 'Children', 'Paperback', 'English', 96, '2014-05-01', '19.8 x 13.0  x 0.8', 100, 'Children''s', 'Someone has stolen all of the ripe strawberries from Mika''s garden! The Secret Mystery Club is determined to work out who it was. Could it have been the gardener? Or was it the neighbours who just made a batch of strawberry jam? Whoever it was, they won''t get far - not with the SMC on the case.', 56000, 'strawberry-thief.jpg'),
(15, 'A Tiny Bit Lucky', '9781743625347', '1743625340', 'Children', 'Paperback', 'English', 256, '2014-05-01', '19.2 x 15.2 ', 280, 'Children''s', 'Me, Derek and Norman need some Serious band practice for the Rockwekly Bandbattle Audition But i''m not panicking becasue we have LOADS of time... (I think?) From the winner of the Roald Dahl Funny Prize, the Red House Children''s Book Award, the Waterstones Children''s Book Prize and the Blue Peter Best Story Book Award 2013, comes the seventh amazing instalment of the Tom Gates adventures. ', 222000, 'a-tiny-bit-lucky.jpg'),
(16, 'Try Time', '9780857982469', '085798246X', 'Children', 'Paperback ', 'English', 144, '2014-05-01', '19.7 x 13.0  x 1.2', 130, 'Children''s', 'Josh can play footy. He''s fast and fleet-footed and a blur down the sideline. But every time he steps onto the field a stampede of elephant-sized butterflies invade his stomach and he fumbles the ball.\r\n\r\nHaving his footy-mad grandad screaming from the sidelines doesn''t help. To top it off, he blows an easy try and loses his team the opening game of the season. Josh starts thinking about giving up football forever. That is, until NRL legend and Josh''s hero, Billy Slater, turns up at training one day.', 87999, 'try-time.jpg'),
(17, 'Banana Kick', '9780857982667', '0857982664', 'Children', 'Paperback', 'English', 128, '2014-05-01', '19.7 x 13.0  x 1.2 ', 130, 'Children''s', 'Junior is the youngest player for the West Hill Ravens. He is also the biggest. Everyone on the team starts to call him Cannonball because, when he makes a bust, he''s virtually unstoppable.\r\n\r\nEven though Junior is helping his team score more tries than ever, no one seems to be able to see past his size. When team mentor, Billy Slater, sets the Ravens a challenge, Junior''s bad feeling gets even worse. \r\n', 56000, 'banana-kick.jpg'),
(18, 'Missing, Presumed Evil', '9781405258678', '1405258675', 'Children ', 'Paperback', 'English', 368, '2014-05-05', '19.8 x 12.9  x 2.6', 230, 'Children''s', 'This title shows page-turning adventures for fans of Percy Jackson and Harry Potter. Jack and Jaide Shield finally learn what it really means to be a warden in training as they pit their wits and their gifts against a rival - who is also a troubletwister! But as they explore the forbidden dark of the Evil dimension, they also have to come to terms with the truth about Grandma X''s twin sister and face their greatest challenge ever...\r\n', 321000, 'missing-presumed-evil.jpg'),
(19, 'A World Without Princess', '9780007502813', '0007502818', 'Children', 'Paperback', 'English', 448, '2014-05-01', '19.8 x 13.1  x 2.4', 300, 'Children''s', 'After saving themselves and their fellow students from a life pitched against one another, Sophie and Agatha are back home again, living happily ever after. But life isn''t exactly a fairy tale...\r\n\r\nWhen Agatha secretly wishes she''d chosen a different happy ending with Prince Tedros, the gates to the School for Good and Evil open once again. But everything has changed and a happy ending seems further away than ever... ', 438000, 'a-world-without-princes.jpg'),
(20, 'Everithing Eyes', '9781452119618', '1452119619', 'General ', 'Hardcover', 'English ', 120, '2014-05-01', '21.1 x 15.9  x 1.3', 120, 'Lifestyle', 'In All About Eyes, bestselling author and global makeup mogul Bobbi Brown shares her expert tips for getting beautiful, show stopping eyes. The book covers basic eye care, essential makeup techniques and products, step-by-steps for stunning go-to looks (such as smoky, sparkly and natural), and tips for selecting eyewear and wearing makeup with glasses. Packaged as a small, chic, take-anywhere hardcover, this accessible manual has something for women with all different types of eyes! \r\n', 90000, 'everything-eyes.jpg'),
(21, 'Vintage Wedding Flowers', '9780857831873', '0857831879', 'General', 'Hardcover', 'English ', 176, '2014-05-01', '25.0 x 21.0  x 2.3', 910, 'Lifestyle', 'Vic Brotherson believes that wedding flowers should express the character and individuality of a couple. In Vintage Wedding Flowers she provides ideas and inspiration for everything from bouquets to buttonholes, to table dressings, and corsages – and to suit all possible budgets. Chapters include Classic Flora, which considers traditional white and green displays; Graceful Rose, which has soft and graceful arrangements; Crazy Iris, for the more adventurous bride; and Romantic Violet, for those wanting a magical, dreamy feel. Full of beautifully shot colour photographs and helpful, step-by-step instructions, Vintage Wedding Flowers helps you create beautiful, timeless wedding flowers from simple blooms whether you plan to do the flowers yourself or employ someone to do them for you.\r\n', 43000, 'vintage-wedding-flowers.jpg'),
(22, 'Save With Jamie', '9780718158149', '0718158148', 'General ', 'Hardcover', 'English', 288, '2013-09-05', '24.6 x 20.1  x 3.0 ', 700, 'Lifestyle', 'This year, I''ve got the message loud and clear that as everyone comes under bigger and bigger financial pressure, they want help to cook tasty, nutritious food on a budget - so this book was born completely out of public demand. Save with Jamie draws on knowledge and cooking skills to help you make better choices, showing you how to buy economically and efficiently, get the most out of your ingredients, save time and prevent food waste. \r\n\r\nAnd there''s no compromise - I''m talking big flavours, comfort food that makes you happy, and colourful, optimistic dishes. Our biggest luxury is knowledge, whether times are hard or not, so get kitchen smart and smash the recession.  \r\n', 234990, 'save-with-jamie.jpg'),
(23, 'Sane The World', '9781444755756', '1444755757', 'General', 'Paperback', 'English', 272, '2014-04-08', '19.6 x 13.1  x 1.9', 200, 'Family and Health', 'How is it that our own minds can jeopardize our sanity?\r\n\r\nWith the experience of her own periods of depression and a Masters degree from Oxford in Mindfulness-based Cognitive Therapy to draw from, Ruby Wax explains how our busy, chattering, self-critical thoughts drive us to anxiety and stress.\r\n\r\nIf we are to break the cycle, we need to understand how our brains work, rewire our thinking and find calm in a frenetic world.\r\n\r\nHelping you become the master, not the slave, of your mind, here is the manual to saner living.  \r\n', 123000, 'sane-new-world.jpg'),
(24, 'The Twelfth Raven', '9781742585635', '1742585639', 'General', 'Paperback', 'English', 336, '2014-03-03', '23.4 x 15.3  x 1.8', 500, 'Family and Health', 'When Doris Brett''s fit, healthy 59-year-old husband Martin had a stroke, they were unexpectedly thrown into a journey of discovery. What began as a minor stroke turned into a golf-ball sized blood clot on his brain, followed by a life-threatening heart condition. \r\n\r\nLater Brett learned that she carried the potentially deadly BRCA1 genetic mutation. However - due largely to Doris'' research into brain plasticity and the neurotherapy techniques she implemented - Martin''s recovery was exceptional and he has now returned to all of his pre-stroke activities.\r\n\r\nThe Twelfth Raven is a literary journey through a series of crises, and an inspirational story of recovery after stroke. Doris Brett''s brave and unflinching memoir offers hope to the hundreds of thousands of people affected by stroke, through the active intervention Doris conducted and the excellent results that were achieved.  \r\n', 433000, 'the-twelfth-raven.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `login`
--

CREATE TABLE IF NOT EXISTS `login` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

--
-- Dumping data for table `login`
--

INSERT INTO `login` (`id`, `email`, `password`) VALUES
(1, 'admin@9bookstore.com', '21232f297a57a5a743894a0e4a801fc3'),
(2, 'guest@9bookstore.com', '084e0343a0486ff05530df6c705c8bb4');

-- --------------------------------------------------------

--
-- Table structure for table `temp_login`
--

CREATE TABLE IF NOT EXISTS `temp_login` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `key` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=34 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
